# Generated by Django 5.2 on 2025-10-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='الكمية في المخزون')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء (دينار)')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع (دينار)')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='الكمية المشتراة')),
                ('date_achat', models.DateField(auto_now_add=True, verbose_name='تاريخ الشراء')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Siliana.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='الكمية المباعة')),
                ('date_vente', models.DateField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Siliana.produit')),
            ],
        ),
    ]
