# Generated by Django 5.2 on 2025-10-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Siliana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='الاسم')),
                ('wilaya', models.CharField(max_length=100, verbose_name='الولاية')),
                ('ville', models.CharField(max_length=100, verbose_name='المدينة')),
                ('telephone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='الكمية')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Siliana.order')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Siliana.produit')),
            ],
        ),
    ]
