# Generated by Django 5.2 on 2025-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Siliana', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
