# Generated by Django 5.2 on 2025-10-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Siliana', '0004_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المنتج'),
        ),
    ]
